"""
visualizations.py — RetailPulse Visualizations Page
Source: RETAILPULSE_FRONTEND.md Page 9 — Visualizations.
"""
import streamlit as st


# Known visualization filenames to fetch
VISUALIZATION_FILES = [
    "dashboard.png",
    "chart1.png",
    "chart2.png",
    "chart3.png",
    "chart4.png",
]


def render():
    from custom_styles import apply_theme, section_header, show_error
    from client import RetailPulseClient
    from config import BASE_URL

    apply_theme()
    section_header("Visualizations")
    st.markdown("Static dashboard charts generated by the pipeline.")
    st.divider()

    client = RetailPulseClient(BASE_URL)

    # Fetch each image individually — per-image error, never hide all on one failure
    images = {}
    errors = {}

    for filename in VISUALIZATION_FILES:
        with st.spinner(f"Loading {filename}..."):
            try:
                img_bytes = client.get_visualization(filename)
                images[filename] = img_bytes
            except Exception as e:
                err = str(e).lower()
                if "404" in err or "not found" in err:
                    # Silently skip — file may not exist yet
                    pass
                else:
                    errors[filename] = str(e)

    # Show per-image errors (non-404)
    for filename, err_msg in errors.items():
        show_error(f"Could not load {filename}: {err_msg}")

    if not images:
        st.info("No visualizations available. Run the pipeline first to generate charts.")
        return

    # ── Display in clean grid layout ──────────────────────────────────────────
    image_list = list(images.items())
    num_images = len(image_list)

    # First image (dashboard.png) gets full width
    if image_list and image_list[0][0] == "dashboard.png":
        filename, img_bytes = image_list[0]
        st.markdown(
            f"""
            <div class="viz-card">
                <p style='font-weight: 600; color: #111827; font-family: Montserrat, sans-serif; margin-bottom: 12px;'>{filename}</p>
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.image(img_bytes, caption=filename, use_container_width=True)
        remaining = image_list[1:]
    else:
        remaining = image_list

    # Remaining images in 2-column grid
    if remaining:
        st.divider()
        st.subheader("Individual Charts")
        for i in range(0, len(remaining), 2):
            cols = st.columns(2)
            for j, (filename, img_bytes) in enumerate(remaining[i : i + 2]):
                with cols[j]:
                    st.image(img_bytes, caption=filename, use_container_width=True)
